/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as BoasVindasRouteImport } from './routes/boas-vindas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DescobrirRouteImport } from './routes/descobrir'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as MinhaAtividadeRouteImport } from './routes/minha-atividade'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminComentariosRouteImport } from './routes/admin/comentarios'
import { Route as AdminDenunciasRouteImport } from './routes/admin/denuncias'
import { Route as AdminEmpresasRouteImport } from './routes/admin/empresas'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminPostagensRouteImport } from './routes/admin/postagens'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminVagasRouteImport } from './routes/admin/vagas'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes/index'
import { Route as ConfiguracoesAcessibilidadeRouteImport } from './routes/configuracoes/acessibilidade'
import { Route as ConfiguracoesBloqueadosRouteImport } from './routes/configuracoes/bloqueados'
import { Route as ConfiguracoesContaRouteImport } from './routes/configuracoes/conta'
import { Route as ConfiguracoesNotificacoesRouteImport } from './routes/configuracoes/notificacoes'
import { Route as ConfiguracoesPrivacidadeRouteImport } from './routes/configuracoes/privacidade'
import { Route as ConfiguracoesSegurancaRouteImport } from './routes/configuracoes/seguranca'
import { Route as ConfiguracoesSenhaRouteImport } from './routes/configuracoes/senha'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCandidatoRouteImport } from './routes/dashboard/candidato'
import { Route as DashboardEmpresaRouteImport } from './routes/dashboard/empresa'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PerfilUsuarioIdRouteImport } from './routes/perfil.$usuarioId'
import { Route as PostagemPostagemIdRouteImport } from './routes/postagem.$postagemId'
import { Route as VagaVagaIdRouteImport } from './routes/vaga.$vagaId'
import { Route as AdminDenunciasIndexRouteImport } from './routes/admin/denuncias.index'
import { Route as AdminDenunciasDenunciaIdRouteImport } from './routes/admin/denuncias.$denunciaId'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin/usuarios.index'
import { Route as AdminUsuariosUsuarioIdRouteImport } from './routes/admin/usuarios.$usuarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BoasVindasRoute = BoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DescobrirRoute = DescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAtividadeRoute = MinhaAtividadeRouteImport.update({
  id: '/minha-atividade',
  path: '/minha-atividade',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostagensRoute = AdminPostagensRouteImport.update({
  id: '/postagens',
  path: '/postagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVagasRoute = AdminVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AdminRoute,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesAcessibilidadeRoute =
  ConfiguracoesAcessibilidadeRouteImport.update({
    id: '/configuracoes/acessibilidade',
    path: '/configuracoes/acessibilidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesBloqueadosRoute = ConfiguracoesBloqueadosRouteImport.update({
  id: '/configuracoes/bloqueados',
  path: '/configuracoes/bloqueados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesContaRoute = ConfiguracoesContaRouteImport.update({
  id: '/configuracoes/conta',
  path: '/configuracoes/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesNotificacoesRoute =
  ConfiguracoesNotificacoesRouteImport.update({
    id: '/configuracoes/notificacoes',
    path: '/configuracoes/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesPrivacidadeRoute =
  ConfiguracoesPrivacidadeRouteImport.update({
    id: '/configuracoes/privacidade',
    path: '/configuracoes/privacidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesSegurancaRoute = ConfiguracoesSegurancaRouteImport.update({
  id: '/configuracoes/seguranca',
  path: '/configuracoes/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesSenhaRoute = ConfiguracoesSenhaRouteImport.update({
  id: '/configuracoes/senha',
  path: '/configuracoes/senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCandidatoRoute = DashboardCandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmpresaRoute = DashboardEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => DashboardRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilUsuarioIdRoute = PerfilUsuarioIdRouteImport.update({
  id: '/$usuarioId',
  path: '/$usuarioId',
  getParentRoute: () => PerfilRoute,
} as any)
const PostagemPostagemIdRoute = PostagemPostagemIdRouteImport.update({
  id: '/postagem/$postagemId',
  path: '/postagem/$postagemId',
  getParentRoute: () => rootRouteImport,
} as any)
const VagaVagaIdRoute = VagaVagaIdRouteImport.update({
  id: '/vaga/$vagaId',
  path: '/vaga/$vagaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDenunciasIndexRoute = AdminDenunciasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDenunciasRoute,
} as any)
const AdminDenunciasDenunciaIdRoute =
  AdminDenunciasDenunciaIdRouteImport.update({
    id: '/$denunciaId',
    path: '/$denunciaId',
    getParentRoute: () => AdminDenunciasRoute,
  } as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsuariosRoute,
} as any)
const AdminUsuariosUsuarioIdRoute = AdminUsuariosUsuarioIdRouteImport.update({
  id: '/$usuarioId',
  path: '/$usuarioId',
  getParentRoute: () => AdminUsuariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/descobrir': typeof DescobrirRoute
  '/entrar': typeof EntrarRoute
  '/feed': typeof FeedRoute
  '/mensagens': typeof MensagensRoute
  '/minha-atividade': typeof MinhaAtividadeRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre-nos': typeof SobreNosRoute
  '/vagas': typeof VagasRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/denuncias': typeof AdminDenunciasRouteWithChildren
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/postagens': typeof AdminPostagensRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/admin/vagas': typeof AdminVagasRoute
  '/configuracoes/acessibilidade': typeof ConfiguracoesAcessibilidadeRoute
  '/configuracoes/bloqueados': typeof ConfiguracoesBloqueadosRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/privacidade': typeof ConfiguracoesPrivacidadeRoute
  '/configuracoes/seguranca': typeof ConfiguracoesSegurancaRoute
  '/configuracoes/senha': typeof ConfiguracoesSenhaRoute
  '/dashboard/candidato': typeof DashboardCandidatoRoute
  '/dashboard/empresa': typeof DashboardEmpresaRoute
  '/perfil/$usuarioId': typeof PerfilUsuarioIdRoute
  '/postagem/$postagemId': typeof PostagemPostagemIdRoute
  '/vaga/$vagaId': typeof VagaVagaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/admin/denuncias/$denunciaId': typeof AdminDenunciasDenunciaIdRoute
  '/admin/usuarios/$usuarioId': typeof AdminUsuariosUsuarioIdRoute
  '/admin/denuncias/': typeof AdminDenunciasIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/descobrir': typeof DescobrirRoute
  '/entrar': typeof EntrarRoute
  '/feed': typeof FeedRoute
  '/mensagens': typeof MensagensRoute
  '/minha-atividade': typeof MinhaAtividadeRoute
  '/notificacoes': typeof NotificacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre-nos': typeof SobreNosRoute
  '/vagas': typeof VagasRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/postagens': typeof AdminPostagensRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/configuracoes/acessibilidade': typeof ConfiguracoesAcessibilidadeRoute
  '/configuracoes/bloqueados': typeof ConfiguracoesBloqueadosRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/privacidade': typeof ConfiguracoesPrivacidadeRoute
  '/configuracoes/seguranca': typeof ConfiguracoesSegurancaRoute
  '/configuracoes/senha': typeof ConfiguracoesSenhaRoute
  '/dashboard/candidato': typeof DashboardCandidatoRoute
  '/dashboard/empresa': typeof DashboardEmpresaRoute
  '/perfil/$usuarioId': typeof PerfilUsuarioIdRoute
  '/postagem/$postagemId': typeof PostagemPostagemIdRoute
  '/vaga/$vagaId': typeof VagaVagaIdRoute
  '/admin': typeof AdminIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/admin/denuncias/$denunciaId': typeof AdminDenunciasDenunciaIdRoute
  '/admin/usuarios/$usuarioId': typeof AdminUsuariosUsuarioIdRoute
  '/admin/denuncias': typeof AdminDenunciasIndexRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/descobrir': typeof DescobrirRoute
  '/entrar': typeof EntrarRoute
  '/feed': typeof FeedRoute
  '/mensagens': typeof MensagensRoute
  '/minha-atividade': typeof MinhaAtividadeRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre-nos': typeof SobreNosRoute
  '/vagas': typeof VagasRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/denuncias': typeof AdminDenunciasRouteWithChildren
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/postagens': typeof AdminPostagensRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/admin/vagas': typeof AdminVagasRoute
  '/configuracoes/acessibilidade': typeof ConfiguracoesAcessibilidadeRoute
  '/configuracoes/bloqueados': typeof ConfiguracoesBloqueadosRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/privacidade': typeof ConfiguracoesPrivacidadeRoute
  '/configuracoes/seguranca': typeof ConfiguracoesSegurancaRoute
  '/configuracoes/senha': typeof ConfiguracoesSenhaRoute
  '/dashboard/candidato': typeof DashboardCandidatoRoute
  '/dashboard/empresa': typeof DashboardEmpresaRoute
  '/perfil/$usuarioId': typeof PerfilUsuarioIdRoute
  '/postagem/$postagemId': typeof PostagemPostagemIdRoute
  '/vaga/$vagaId': typeof VagaVagaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/admin/denuncias/$denunciaId': typeof AdminDenunciasDenunciaIdRoute
  '/admin/usuarios/$usuarioId': typeof AdminUsuariosUsuarioIdRoute
  '/admin/denuncias/': typeof AdminDenunciasIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/boas-vindas'
    | '/cadastro'
    | '/confirmar-email'
    | '/dashboard'
    | '/descobrir'
    | '/entrar'
    | '/feed'
    | '/mensagens'
    | '/minha-atividade'
    | '/notificacoes'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sobre-nos'
    | '/vagas'
    | '/admin/comentarios'
    | '/admin/denuncias'
    | '/admin/empresas'
    | '/admin/logs'
    | '/admin/postagens'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/configuracoes/acessibilidade'
    | '/configuracoes/bloqueados'
    | '/configuracoes/conta'
    | '/configuracoes/notificacoes'
    | '/configuracoes/privacidade'
    | '/configuracoes/seguranca'
    | '/configuracoes/senha'
    | '/dashboard/candidato'
    | '/dashboard/empresa'
    | '/perfil/$usuarioId'
    | '/postagem/$postagemId'
    | '/vaga/$vagaId'
    | '/admin/'
    | '/configuracoes/'
    | '/dashboard/'
    | '/perfil/'
    | '/admin/denuncias/$denunciaId'
    | '/admin/usuarios/$usuarioId'
    | '/admin/denuncias/'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/boas-vindas'
    | '/cadastro'
    | '/confirmar-email'
    | '/descobrir'
    | '/entrar'
    | '/feed'
    | '/mensagens'
    | '/minha-atividade'
    | '/notificacoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sobre-nos'
    | '/vagas'
    | '/admin/comentarios'
    | '/admin/empresas'
    | '/admin/logs'
    | '/admin/postagens'
    | '/admin/vagas'
    | '/configuracoes/acessibilidade'
    | '/configuracoes/bloqueados'
    | '/configuracoes/conta'
    | '/configuracoes/notificacoes'
    | '/configuracoes/privacidade'
    | '/configuracoes/seguranca'
    | '/configuracoes/senha'
    | '/dashboard/candidato'
    | '/dashboard/empresa'
    | '/perfil/$usuarioId'
    | '/postagem/$postagemId'
    | '/vaga/$vagaId'
    | '/admin'
    | '/configuracoes'
    | '/dashboard'
    | '/perfil'
    | '/admin/denuncias/$denunciaId'
    | '/admin/usuarios/$usuarioId'
    | '/admin/denuncias'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/boas-vindas'
    | '/cadastro'
    | '/confirmar-email'
    | '/dashboard'
    | '/descobrir'
    | '/entrar'
    | '/feed'
    | '/mensagens'
    | '/minha-atividade'
    | '/notificacoes'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sobre-nos'
    | '/vagas'
    | '/admin/comentarios'
    | '/admin/denuncias'
    | '/admin/empresas'
    | '/admin/logs'
    | '/admin/postagens'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/configuracoes/acessibilidade'
    | '/configuracoes/bloqueados'
    | '/configuracoes/conta'
    | '/configuracoes/notificacoes'
    | '/configuracoes/privacidade'
    | '/configuracoes/seguranca'
    | '/configuracoes/senha'
    | '/dashboard/candidato'
    | '/dashboard/empresa'
    | '/perfil/$usuarioId'
    | '/postagem/$postagemId'
    | '/vaga/$vagaId'
    | '/admin/'
    | '/configuracoes/'
    | '/dashboard/'
    | '/perfil/'
    | '/admin/denuncias/$denunciaId'
    | '/admin/usuarios/$usuarioId'
    | '/admin/denuncias/'
    | '/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  BoasVindasRoute: typeof BoasVindasRoute
  CadastroRoute: typeof CadastroRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DescobrirRoute: typeof DescobrirRoute
  EntrarRoute: typeof EntrarRoute
  FeedRoute: typeof FeedRoute
  MensagensRoute: typeof MensagensRoute
  MinhaAtividadeRoute: typeof MinhaAtividadeRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreNosRoute: typeof SobreNosRoute
  VagasRoute: typeof VagasRoute
  ConfiguracoesAcessibilidadeRoute: typeof ConfiguracoesAcessibilidadeRoute
  ConfiguracoesBloqueadosRoute: typeof ConfiguracoesBloqueadosRoute
  ConfiguracoesContaRoute: typeof ConfiguracoesContaRoute
  ConfiguracoesNotificacoesRoute: typeof ConfiguracoesNotificacoesRoute
  ConfiguracoesPrivacidadeRoute: typeof ConfiguracoesPrivacidadeRoute
  ConfiguracoesSegurancaRoute: typeof ConfiguracoesSegurancaRoute
  ConfiguracoesSenhaRoute: typeof ConfiguracoesSenhaRoute
  PostagemPostagemIdRoute: typeof PostagemPostagemIdRoute
  VagaVagaIdRoute: typeof VagaVagaIdRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boas-vindas': {
      id: '/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof BoasVindasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descobrir': {
      id: '/descobrir'
      path: '/descobrir'
      fullPath: '/descobrir'
      preLoaderRoute: typeof DescobrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-atividade': {
      id: '/minha-atividade'
      path: '/minha-atividade'
      fullPath: '/minha-atividade'
      preLoaderRoute: typeof MinhaAtividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/postagens': {
      id: '/admin/postagens'
      path: '/postagens'
      fullPath: '/admin/postagens'
      preLoaderRoute: typeof AdminPostagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vagas': {
      id: '/admin/vagas'
      path: '/vagas'
      fullPath: '/admin/vagas'
      preLoaderRoute: typeof AdminVagasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/acessibilidade': {
      id: '/configuracoes/acessibilidade'
      path: '/configuracoes/acessibilidade'
      fullPath: '/configuracoes/acessibilidade'
      preLoaderRoute: typeof ConfiguracoesAcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/bloqueados': {
      id: '/configuracoes/bloqueados'
      path: '/configuracoes/bloqueados'
      fullPath: '/configuracoes/bloqueados'
      preLoaderRoute: typeof ConfiguracoesBloqueadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/conta': {
      id: '/configuracoes/conta'
      path: '/configuracoes/conta'
      fullPath: '/configuracoes/conta'
      preLoaderRoute: typeof ConfiguracoesContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/notificacoes': {
      id: '/configuracoes/notificacoes'
      path: '/configuracoes/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof ConfiguracoesNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/privacidade': {
      id: '/configuracoes/privacidade'
      path: '/configuracoes/privacidade'
      fullPath: '/configuracoes/privacidade'
      preLoaderRoute: typeof ConfiguracoesPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/seguranca': {
      id: '/configuracoes/seguranca'
      path: '/configuracoes/seguranca'
      fullPath: '/configuracoes/seguranca'
      preLoaderRoute: typeof ConfiguracoesSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/senha': {
      id: '/configuracoes/senha'
      path: '/configuracoes/senha'
      fullPath: '/configuracoes/senha'
      preLoaderRoute: typeof ConfiguracoesSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/candidato': {
      id: '/dashboard/candidato'
      path: '/candidato'
      fullPath: '/dashboard/candidato'
      preLoaderRoute: typeof DashboardCandidatoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/empresa': {
      id: '/dashboard/empresa'
      path: '/empresa'
      fullPath: '/dashboard/empresa'
      preLoaderRoute: typeof DashboardEmpresaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/$usuarioId': {
      id: '/perfil/$usuarioId'
      path: '/$usuarioId'
      fullPath: '/perfil/$usuarioId'
      preLoaderRoute: typeof PerfilUsuarioIdRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/postagem/$postagemId': {
      id: '/postagem/$postagemId'
      path: '/postagem/$postagemId'
      fullPath: '/postagem/$postagemId'
      preLoaderRoute: typeof PostagemPostagemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaga/$vagaId': {
      id: '/vaga/$vagaId'
      path: '/vaga/$vagaId'
      fullPath: '/vaga/$vagaId'
      preLoaderRoute: typeof VagaVagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/denuncias/': {
      id: '/admin/denuncias/'
      path: '/'
      fullPath: '/admin/denuncias/'
      preLoaderRoute: typeof AdminDenunciasIndexRouteImport
      parentRoute: typeof AdminDenunciasRoute
    }
    '/admin/denuncias/$denunciaId': {
      id: '/admin/denuncias/$denunciaId'
      path: '/$denunciaId'
      fullPath: '/admin/denuncias/$denunciaId'
      preLoaderRoute: typeof AdminDenunciasDenunciaIdRouteImport
      parentRoute: typeof AdminDenunciasRoute
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
    '/admin/usuarios/$usuarioId': {
      id: '/admin/usuarios/$usuarioId'
      path: '/$usuarioId'
      fullPath: '/admin/usuarios/$usuarioId'
      preLoaderRoute: typeof AdminUsuariosUsuarioIdRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
  }
}

interface AdminDenunciasRouteChildren {
  AdminDenunciasDenunciaIdRoute: typeof AdminDenunciasDenunciaIdRoute
  AdminDenunciasIndexRoute: typeof AdminDenunciasIndexRoute
}

const AdminDenunciasRouteChildren: AdminDenunciasRouteChildren = {
  AdminDenunciasDenunciaIdRoute: AdminDenunciasDenunciaIdRoute,
  AdminDenunciasIndexRoute: AdminDenunciasIndexRoute,
}

const AdminDenunciasRouteWithChildren = AdminDenunciasRoute._addFileChildren(
  AdminDenunciasRouteChildren,
)

interface AdminUsuariosRouteChildren {
  AdminUsuariosUsuarioIdRoute: typeof AdminUsuariosUsuarioIdRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

const AdminUsuariosRouteChildren: AdminUsuariosRouteChildren = {
  AdminUsuariosUsuarioIdRoute: AdminUsuariosUsuarioIdRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}

const AdminUsuariosRouteWithChildren = AdminUsuariosRoute._addFileChildren(
  AdminUsuariosRouteChildren,
)

interface AdminRouteChildren {
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminDenunciasRoute: typeof AdminDenunciasRouteWithChildren
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPostagensRoute: typeof AdminPostagensRoute
  AdminUsuariosRoute: typeof AdminUsuariosRouteWithChildren
  AdminVagasRoute: typeof AdminVagasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComentariosRoute: AdminComentariosRoute,
  AdminDenunciasRoute: AdminDenunciasRouteWithChildren,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPostagensRoute: AdminPostagensRoute,
  AdminUsuariosRoute: AdminUsuariosRouteWithChildren,
  AdminVagasRoute: AdminVagasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCandidatoRoute: typeof DashboardCandidatoRoute
  DashboardEmpresaRoute: typeof DashboardEmpresaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCandidatoRoute: DashboardCandidatoRoute,
  DashboardEmpresaRoute: DashboardEmpresaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PerfilRouteChildren {
  PerfilUsuarioIdRoute: typeof PerfilUsuarioIdRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilUsuarioIdRoute: PerfilUsuarioIdRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AjudaRoute: AjudaRoute,
  BoasVindasRoute: BoasVindasRoute,
  CadastroRoute: CadastroRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DescobrirRoute: DescobrirRoute,
  EntrarRoute: EntrarRoute,
  FeedRoute: FeedRoute,
  MensagensRoute: MensagensRoute,
  MinhaAtividadeRoute: MinhaAtividadeRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreNosRoute: SobreNosRoute,
  VagasRoute: VagasRoute,
  ConfiguracoesAcessibilidadeRoute: ConfiguracoesAcessibilidadeRoute,
  ConfiguracoesBloqueadosRoute: ConfiguracoesBloqueadosRoute,
  ConfiguracoesContaRoute: ConfiguracoesContaRoute,
  ConfiguracoesNotificacoesRoute: ConfiguracoesNotificacoesRoute,
  ConfiguracoesPrivacidadeRoute: ConfiguracoesPrivacidadeRoute,
  ConfiguracoesSegurancaRoute: ConfiguracoesSegurancaRoute,
  ConfiguracoesSenhaRoute: ConfiguracoesSenhaRoute,
  PostagemPostagemIdRoute: PostagemPostagemIdRoute,
  VagaVagaIdRoute: VagaVagaIdRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
